.TH "atomic_masses" 3 "Mon May 12 2025" "My G-CTMQC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
atomic_masses \- The module defines nuclear masses in atomic units\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "real(kind=dp), parameter \fBm_hp\fP = 1836\&.0_dp"
.br
.RI "Proton mass in atomic units\&. "
.ti -1c
.RI "real(kind=dp), parameter \fBm_na\fP = 22\&.989769_dp"
.br
.RI "Na mass in atomic mass units\&. "
.ti -1c
.RI "real(kind=dp), parameter \fBm_i\fP = 126\&.90447_dp"
.br
.RI "I mass in atomic mass units\&. "
.ti -1c
.RI "real(kind=dp), parameter \fBm_br\fP = 79\&.9040_dp"
.br
.RI "Br mass in atomic mass units\&. "
.ti -1c
.RI "real(kind=dp), parameter \fBm_h\fP = 1\&.007825_dp"
.br
.RI "H mass in atomic mass units\&. "
.ti -1c
.RI "real(kind=dp), parameter \fBm_o\fP = 15\&.9994_dp"
.br
.RI "O mass in atomic mass units\&. "
.in -1c
.SH "Detailed Description"
.PP 
The module defines nuclear masses in atomic units\&. 


.PP
\fBAuthor\fP
.RS 4
Federica Agostini, Institut de Chimie Physique, University Paris-Saclay\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My G-CTMQC from the source code\&.
