.TH "kinds" 3 "Mon May 12 2025" "My G-CTMQC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinds \- Definiton of kinds\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBdp\fP =kind(0\&.0D0)"
.br
.RI "Indicator for real double precision\&. "
.ti -1c
.RI "integer, parameter \fBqp\fP =selected_real_kind(12)"
.br
.RI "Indicator for real quadrupole precision\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definiton of kinds\&. 


.PP
\fBAuthor\fP
.RS 4
Federica Agostini, Institut de Chimie Physique, University Paris-Saclay\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My G-CTMQC from the source code\&.
